spring.application.name=demo


spring.ai.google.genai.api-key=sample_key_12345
spring.ai.google.genai.chat.options.model=gemini-2.5-pro
spring.ai.google.genai.embedding.options.model=gemini-embedding-2
spring.ai.google.genai.project-id=sample_project_id_0445537841
spring.ai.google.genai.embedding.options.dimensions=1536
spring.ai.vectorstore.pgvector.initialize-schema=true



spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
