spring.application.name=demo
spring.ai.google.genai.api-key="key"
spring.ai.google.genai.chat.options.model="model"
spring.ai.google.genai.embedding.options.model=text-embedding-004
spring.ai.google.genai.project-id="project id"


spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver


spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.initialize-schema=true
